production:
  :verbose: false
  :pidfile: ./tmp/sidekiq.pid
  :logfile: ./log/sidekiq-production.log
  :concurency: 5
  :queues:
    - [default,1]
development:
  :verbose: true
  :pidfile: ./tmp/sidekiq.pid
  :logfile: ./log/sidekiq-development.log
  :concurency: 5
  :queues:
    - [default,1]
test:
  :verbose: true
  :pidfile: ./tmp/sidekiq.pid
  :logfile: ./log/sidekiq-test.log
  :concurency: 5
  :queues:
    - [default,1]
