production:
  :verbose: false
  :pidfile: ./tmp/sidekiq.pid
  :logfile: ./log/sidekiq-production.log
  :concurrency: 5
development:
  :verbose: true
  :pidfile: ./tmp/sidekiq.pid
  :logfile: ./log/sidekiq-development.log
  :concurrency: 5
test:
  :verbose: true
  :pidfile: ./tmp/sidekiq.pid
  :logfile: ./log/sidekiq-test.log
  :concurrency: 5
